### PR TITLE
HERTZ initial implementation

### PR DESCRIPTION
**Pull request by grctest**
I have not yet tested this (quite late right now), however I'd appreciate some input on how I've implemented the HERTZ algorithm based asset in bts_tools.

I've added 'import math' for pi and sin functions.

I've added HERTZ entries here and there.

I've applied a fix to the HERO % to 175 down from 200.

### CODE REVIEW

**Comment by grctest** [comment]
I've been thinking about the [state of the hertz price feed scripts](https://steemit.com/bitshares/@cm-steem/hertz-price-feed-script-updates-september-2017), and there's a couple things which I need to investigate:
* Differences between 'time' and 'pendulum' packages in terms of Unix timestamps.
  * Likelihood: Low
  * Risk: Low. If there was a difference it'd likely be minescule.
  * Solution: Pick the best package. If pendulum - investigate impact within xeroc's python environment.
* Impact of price feed producer's time zone on output Unix timestamps.
  * Likelihood: High
  * Risk: Moderate. 24hr max price feed difference due to time zone difference could be $0.0164
  * Solution: Convert localtime to UTC prior to converting to Unix timestamp.

Can you think of any other possible issues? ([Steem thread](https://steemit.com/bitshares/@cm-steem/hertz-next-area-of-investigation-prior-to-production))

**Comment by wackou** [comment]
hi, thanks for the PR and sorry for not having been more reactive on implementing this. 
A couple of comments:
- could you replace the "magic" numbers with how they have been computed? e.g.:
  ```
  period = ndays * 24 * 60 * 60
  reference_date = pendulum.create(year, month, day)
  price = math.sin((pendulum.utcnow() - reference_date).in_seconds() / period .... )```
  This will make it easier to maintain in the future.
- the MCR for HERO should indeed be 200%, not 175%

as for your doubts:

> Differences between 'time' and 'pendulum' packages in terms of Unix timestamps.

none whatsoever, `pendulum` is a wrapper around `time`, which itselfs calls the time functions of the underlying OS.

> Impact of price feed producer's time zone on output Unix timestamps

all blockchain times are in UTC and price feeds should be using UTC as well. Pendulum uses UTC by default, and you can get the current time using `pendulum.utcnow()`, so it basically does the right thing by default. It is much easier than dealing with the local timezone manually :)

**Comment by grctest** [comment]
Cool, I'll update my bts_tools hertz implementation in the next couple days. I've been working on a stand-alone price feed script recently: https://github.com/BTS-CM/scripts/blob/master/hertz-feed.py

**Comment by grctest** [comment]
> the MCR for HERO should indeed be 200%, not 175%

I made a separate issue regarding this: https://github.com/wackou/bts_tools/issues/33

I disagree, cryptofresh lists it as 200% (likely because of the price feed being published at 200%) however the [official HERO page on collateral](http://docs.hero.global/en/master/collateral.html) lists:

> The maintenance collateral ratio for HERO is:
> ```175%  (2017-05-01)```

**Comment by grctest** [comment]
I've committed an improved version of the hertz price feed script, taking inspiration from the bit20 guys.

Are the following checks required to be able to publish a price feed? Or only when you need to read blockchain data like bit20 does?
```
    if node.type() != 'bts':
        return
    if not node.is_online():
        log.warning('Wallet is offline.')
        return
    if not node.is_synced():
        log.warning('Client is not synced yet.')
        return
    if node.is_locked():
        log.warning('Wallet is locked.')
        return
```

TODO:
* Pick appropriate variable values for:
   * hertz_amplitude - May change from 50% to 25% to be less volatile. Any input on an appropriate value? I created a [simulator & calculator](https://github.com/BTS-CM/scripts/blob/master/hertz_calculator.xlsx) spreadsheet for evaluating this question.
   * hertz_period_days - 30.43 days (365/12) vs 28 days (4 working weeks, peak/trough values on wednesdays.

**Comment by wackou** [comment]
> Are the following checks required to be able to publish a price feed? Or only when you need to read blockchain data like bit20 does?

you are correct, this is only needed when you need to read some data from the blockchain. Given that Hertz is only dependent on the current time, you can safely delete those lines

> Pick appropriate variable values for:
> 
>     - hertz_amplitude - May change from 50% to 25% to be less volatile. Any input on an appropriate value? I created a simulator & calculator spreadsheet for evaluating this question.

no real opinion there, 50% might seem a lot but could display the dynamics of such an asset better. 25% does seem less extreme, though. Hard to say...

>     - hertz_period_days - 30.43 days (365/12) vs 28 days (4 working weeks, peak/trough values on wednesdays.

that's a good one, I would say that I do have a slight preference for 28 days, this gives a little bit of predictability to an asset which is already kind of "funky" (in a good way!). The subdivision in 4 phases (weeks) seem also quite natural, and as you said, allows to have the peaks/troughs always on the same day.

> however the official HERO page on collateral lists:
> >    The maintenance collateral ratio for HERO is:
> >    175% (2017-05-01)

I double checked with xeroc on telegram and he confirmed that we should use 200%, and that the website needs to be updated. I can't find a reference to when/where that was initially said, but as you saw nearly all the witnesses publish with a MCR of 200% and it is often written that HERO is backed by at least twice its value in collateral, so it's a design feature of the asset.


Apart from that, the code looks good to merge!

**Comment by grctest** [comment]
>> Are the following checks required to be able to publish a price feed? Or only when you need to read blockchain data like bit20 does?
>
> you are correct, this is only needed when you need to read some data from the blockchain. Given that Hertz is only dependent on the current time, you can safely delete those lines

Cool, I'll delete these lines then. It's really cool that you can import a key to read a memo.

If we could do this for a burn (or dividend redistribution) address, then we could vote on values for an ABA such as voting to switch between appreciating/depreciating the feed price. Outwith this ABA's scope though for sure.

>> ```- hertz_period_days - 30.43 days (365/12) vs 28 days (4 working weeks, peak/trough values on wednesdays.```
>
> that's a good one, I would say that I do have a slight preference for 28 days, this gives a little bit of predictability to an asset which is already kind of "funky" (in a good way!). The subdivision in 4 phases (weeks) seem also quite natural, and as you said, allows to have the peaks/troughs always on the same day.

Yeah, 28 days seems like the better option. I'll need to apply a phase value (in days), easy enough to do.

>> however the official HERO page on collateral lists:
>>>The maintenance collateral ratio for HERO 
>>>175% (2017-05-01)
>
> I double checked with xeroc on telegram and he confirmed that we should use 200%, and that the website needs to be updated. I can't find a reference to when/where that was initially said, but as you saw nearly all the witnesses publish with a MCR of 200% and it is often written that HERO is backed by at least twice its value in collateral, so it's a design feature of the asset.

Ah, good to know - I'll remove my change from the monitoring.yaml file then, thanks for clearing this up.

**Comment by wackou** [comment]
merged, thanks! I'll start publishing it after releasing next version of bts_tools, I still have a few things I want to clean up before I make the release but hopefully it won't be too long. Cheers!

**Comment by grctest** [comment]
@wackou Hey, could you change this line: https://github.com/wackou/bts_tools/blob/master/bts_tools/feeds.py#L444

To read:
```
hertz_amplitude = 0.14 # 14% fluctuation
```

Thanks 👍

**Pull request merged**
